export const FEEDS_UPDATING = 'FEEDS_UPDATING';
export const FEEDS_UPDATED = 'FEEDS_UPDATED';
export const ENTRIES_UPDATING = 'ENTRIES_UPDATING';
export const ENTRIES_UPDATED = 'ENTRIES_UPDATED';
export const UPDATE_ENTRIES_COUNT = 'UPDATE_ENTRIES_COUNT';