name: github-actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install dependenses
        working-directory: ./server
        run: npm install
      - name: Run tests
        working-directory: ./server
        run: npm test