name: github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: client

      - name: Build client
        run: npm build
        working-directory: client

      - name: Run eslint
        run: npm run lint
        working-directory: client
      
      - name: Run eslint
        run: npm run lint:style
        working-directory: client        
        
      - name: Test client
        run: npm run test
        working-directory: client